# Generated by Django 3.2.16 on 2023-02-14 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='course',
            new_name='chapter',
        ),
    ]
